### ISSUE TITLE
miles conversion lacks precision

### ISSUE THREAD

**Issue by twelve17** [blakeyc/conversions#2]
Hello, and thank you for writing this library.

I noticed that one of my meters -> miles conversion was off:

I expected 24140.16 meters to equal 15 miles, precisely.  But the library was returning 14.991039.  Searching online, I found that 1 meter * 0.000621371 = 1 mile.  However, the library has the conversion with slightly less precision, at [0.000621](https://github.com/blakeyc/conversions/blob/master/src/conversions.js#L82), which partially explains the difference in calculation.

I understand that, even with the greater precision, there are limitations when dealing with floating point arithmetic.  However, with the extra three decimal points on the conversion number, I could round the result to a more precise decimal point.   Would it be possible to append the additional three decimal values to the conversion?

All this being said, maybe the places I found the more accurate conversion value are off?  I'd be curious to hear your input. 

On the chance you find the suggestion acceptable, created a [PR](https://github.com/blakeyc/conversions/pull/3) with the change.

Thanks!

**Comment by blakeyc** [comment]
Thanks for the PR, it has been merged and update published to NPM and released for bower.
